using System.Security.Cryptography;
using Org.BouncyCastle.Crypto.Parameters;
using Org.BouncyCastle.OpenSsl;
using Org.BouncyCastle.Pkcs;
using SBQR.Modules.KeyCustody.Domain.Interfaces;

namespace SBQR.Modules.KeyCustody.Infrastructure.Cryptography;

/// <summary>
/// Default <see cref="IKeyPairGenerator"/> implementation. Generates an Ed25519
/// keypair using <c>System.Security.Cryptography.RandomNumberGenerator</c> for
/// the seed, then uses BouncyCastle's PKCS#8 / SPKI writers to produce the
/// canonical PEM strings the rest of the lifecycle flow expects.
///
/// <para>
/// Why BouncyCastle here: the .NET BCL has
/// <c>System.Security.Cryptography.Ed25519</c> for signing, but it doesn't yet
/// expose a public PEM-export API on the Ed25519 key. We use BouncyCastle only
/// for the SPKI / PKCS#8 wire-format emission; the seed is generated by the
/// BCL's CSPRNG.
/// </para>
/// </summary>
public sealed class Ed25519KeyPairGenerator : IKeyPairGenerator
{
    /// <inheritdoc/>
    public (string PublicKeyPem, byte[] PrivateKeyBytes) GenerateEd25519()
    {
        // 32-byte Ed25519 private seed — fed through BouncyCastle to derive
        // the public half and emit canonical SPKI / PKCS#8 PEMs.
        var seed = RandomNumberGenerator.GetBytes(32);

        var privateKey = new Ed25519PrivateKeyParameters(seed, 0);
        var publicKey = privateKey.GeneratePublicKey();

        var publicPem = EncodePublicKeyPem(publicKey);
        var privatePem = EncodePrivateKeyPem(privateKey);

        // The Domain layer hands privateKeyBytes to the ISigningKeyStore. We
        // use the PKCS#8 PEM bytes here so the same blob is unwrappable later
        // by PemVaultSigningProvider.
        var privateKeyBytes = System.Text.Encoding.ASCII.GetBytes(privatePem);

        return (publicPem, privateKeyBytes);
    }

    private static string EncodePublicKeyPem(Ed25519PublicKeyParameters publicKey)
    {
        // PemWriter understands Ed25519PublicKeyParameters and emits the
        // canonical SPKI "-----BEGIN PUBLIC KEY-----" PEM.
        using var writer = new StringWriter();
        using (var pemWriter = new PemWriter(writer))
        {
            pemWriter.WriteObject(publicKey);
        }
        return writer.ToString();
    }

    private static string EncodePrivateKeyPem(Ed25519PrivateKeyParameters privateKey)
    {
        // PrivateKeyInfoFactory.CreatePrivateKeyInfo wraps the Ed25519 key in
        // the canonical PKCS#8 PrivateKeyInfo structure (with the Ed25519
        // algorithm identifier and the 32-byte seed as the inner OCTET STRING).
        // The resulting PEM is the canonical "-----BEGIN PRIVATE KEY-----" form
        // every Ed25519 library in the ecosystem can read.
        var pkcs8 = PrivateKeyInfoFactory.CreatePrivateKeyInfo(privateKey);

        using var writer = new StringWriter();
        using (var pemWriter = new PemWriter(writer))
        {
            pemWriter.WriteObject(pkcs8);
        }
        return writer.ToString();
    }
}
