// <auto-generated/>
// Global usings for SBQR.SharedKernel.
//
// <ImplicitUsings>enable</ImplicitUsings> in Directory.Build.props brings
// in the framework defaults (System, System.Collections.Generic, etc.).
// Add only project-specific namespace aliases here.
global using System.Reflection;
