using System.Collections.Concurrent;
using SBQR.SharedKernel.Application;

namespace SBQR.Qr.IntegrationTests.Infrastructure;

/// <summary>In-memory IAuditLogger capturing every entry for assertions.</summary>
public sealed class CapturingAuditLogger : IAuditLogger
{
    private readonly ConcurrentQueue<AuditEntry> _entries = new();

    public IReadOnlyList<AuditEntry> Entries => _entries.ToArray();

    /// <summary>
    /// Clear all captured entries. Useful in tests that stage state
    /// (e.g. register a tenant) and want to assert only on the audit
    /// rows generated by the action under test, not the staging actions.
    /// </summary>
    public void Clear() => _entries.Clear();

    public Task LogAsync(AuditEntry entry, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(entry);
        _entries.Enqueue(entry);
        return Task.CompletedTask;
    }
}

/// <summary>
/// Test <see cref="ICurrentTenant"/> the flow drives directly: set
/// <see cref="TenantId"/> to the issuing tenant before dispatching
/// generation commands (mirrors what the host's JWT-claim middleware does
/// per request).
/// </summary>
public sealed class MutableCurrentTenant : ICurrentTenant
{
    public Guid TenantId { get; set; }
}
